global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'proposta-api'
    static_configs:
      - targets: ['proposta-api:5001']
    metrics_path: '/metrics'

  - job_name: 'contratacao-api'
    static_configs:
      - targets: ['contratacao-api:5002']
    metrics_path: '/metrics'
